version: "2"
services:
  front:
    build:
      context: .
      dockerfile: ./Commenlyzer-front/Dockerfile
    image: front-prensa
    container_name: "front-debug"

    command: ./node_modules/@vue/cli-service/bin/vue-cli-service.js  serve --host 0.0.0.0 --port 8081

    ports:
      - 8080:8081

    volumes:
      - ./Commenlyzer-front:/app

    environment:
      - PYTHONPATH=/Crawler
      - MONGO_URI=mongodb://mongodb:27017/elchismoso
      - REAL_PROCESS=1
