version: '2'
services:
  server:
    build: ./backend-observatorio
    container_name: "prensa"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/elchismoso
    volumes:
        - .:/backend-observatorio
    ports:
      - 8000:8000
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.0.6
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet