version: '2'

services:
  caddy:
    build:
      context: .
      dockerfile: ./Dockerfile-caddy
    image: caddy-api-proxy
    container_name: caddy-api-proxy
    ports:
        - "2015:2015"
    links:
      - server
    depends_on:
      - server
    #volumes:
    #    - ./Caddyfile:/etc/Caddyfile

  server:
    build:
      context: .
      dockerfile: ./backend-observatorio/Dockerfile
    image: prensa
    container_name: "prensa"

    command: python /backend-observatorio/production.py

    ports:
      - 8000:8000
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - CLASSIFIER2_MODEL_PATH=/models/so.joblib
      - CLASSIFIER_MODEL_PATH=/models/pnn.joblib
      - VECTORIZER_MODEL_PATH=/models/cv.joblib
      - PYTHONPATH=/Crawler
      - MONGO_URI=mongodb://mongodb:27017/elchismoso
      - REAL_PROCESS=1

  mongodb:
    image: mongo:4.2
    container_name: "prensamongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - prensamongodata:/data/db
    ports:
        - 27017:27017
    command: mongod --wiredTigerCacheSizeGB=0.5
    # --wiredTigerCacheSizeGB=n limit the amount of ram used to n

volumes:
    prensamongodata: