version: '2'
services:
  server:
    build:
      context: .
      dockerfile: ./backend-observatorio/Dockerfile
    image: prensa
    container_name: "prensa"

    # command: cd / && python /backend-observatorio/production.py
    ports:
      - 8000:8000
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - PYTHONPATH=/Crawler
      - MONGO_URI=mongodb://mongodb:27017/elchismoso
      - REAL_PROCESS=1

  mongodb:
    image: mongo:4.0.6
    container_name: "prensamongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --wiredTigerCacheSizeGB=2
    # --wiredTigerCacheSizeGB=n limit the amount of ram used to n